# https://linuxize.com/post/how-to-mount-cifs-windows-share-on-linux/
- name: Install sshfs
  ansible.builtin.package:
    name: "{{ package }}"
    state: latest
  become: true
  loop:
    - sshfs
  loop_control:
    loop_var: package
- name: Set initial mount options
  ansible.builtin.set_fact:
    sshfs_options: "{{ item.value.options }}"
    sshfs_src: "{{ item.value.user }}@{{ item.value.host }}:{{ item.value.target_path }}"
- name: Create folder {{ item.value.path }}"
  ansible.builtin.file:
    path: "{{ item.value.path }}"
    owner: "{{ item.value.owner | default(ansible_user) }}"
    group: "{{ item.value.group | default(ansible_user) }}"
  become: true
- name: "Mount {{ item.key }}: {{ sshfs_src }} to {{ item.value.path }}"
  ansible.posix.mount:
    path: "{{ item.value.path }}"
    src: "{{ sshfs_src }}"
    fstype: fuse.sshfs
    opts: "{{ sshfs_options }}"
    state: mounted
  become: true
  when: item.value.mounted is undefined or item.value.mounted
- name: "Unmount {{ item.key }}: {{ item.value.src }} from {{ item.value.path }}"
  ansible.posix.mount:
    path: "{{ item.value.path }}"
    src: "{{ item.value.src }}"
    state: unmounted
  become: true
  when: item.value.mounted is defined and not item.value.mounted
